--- 
:name: vedmak
:repo: git@Lightpower:vedmak.git
:ruby: "1.9"
:stages: 
  :master: 
    :server: net.arzamas-16.org
    :domain: net.arzamas-16.org
    :environment: production
    :app_workers: 1
:dbms: []

